### ISSUE TITLE
Env variables for custom airflow docker images

### ISSUE THREAD

**Issue by EamonKeane** [GoogleCloudPlatform/airflow-operator#10]
Just giving this a spin with my own images and one of the reasons it doesn't currently work for me is that certain env variables (`AIRFLOW__CORE__SQL_ALCHEMY_CONN` and `AIRFLOW__CORE__FERNET_KEY` in particular) are composed in the `entrypoint.sh` as opposed to directly from env vars. It appears the airflow docker image is based on `https://github.com/puckel/docker-airflow`, is that correct? Are there reasons why the airflow Dockerfile wouldn't be part of this repo? (I'm using a different docker image which doesn't have the same entrypoint as that one.)

In any event, my suggestion would be to try and keep the go build process decoupled from any particular docker image/entrypoint. I see the `args` are configurable in `utils.go`. For sensitive config parameters (e.g. `sql_alchemy_conn` and `fernet_key`), these would probably have to come from kubernetes secrets and be injected as `env_vars` in the UI, scheduler, and k8s worker.

**Comment by barney-s** [comment]
Thanks for reaching out. Thats correct. I should have made it explicit in the readme or userguide (pending). 
Please refer to my airflow-docker repo which is forked from puckel.

I have a pending task to upstream my changes.

https://github.com/barney-s/docker-airflow

changes:
https://github.com/puckel/docker-airflow/compare/master...barney-s:master

Let me know if i can help any other way.

**Comment by EamonKeane** [comment]
thanks I'll have a look.
