### ISSUE TITLE
Airflow 1.10.0

### ISSUE THREAD

**Issue by victornoel** [GoogleCloudPlatform/airflow-operator#14]
Any plan to upgrade to latest airflow that was released not so long ago?

**Comment by tedmiston** [comment]
I'm curious to know the timeline for 1.10 availability as well.

**Comment by barney-s** [comment]
On it. Will try to get it in within a week.

**Comment by victornoel** [comment]
@barney-s any news on that? thanks :)

**Comment by barney-s** [comment]
In progress :) 
https://github.com/GoogleCloudPlatform/airflow-operator/pull/19/files

Pending changes on https://github.com/barney-s/docker-airflow/pull/2

**Comment by barney-s** [comment]
done.
https://github.com/GoogleCloudPlatform/airflow-operator/pull/19
