### ISSUE TITLE
Quickstart Guide references files which do not exist

### ISSUE THREAD

**Issue by chris-vest** [GoogleCloudPlatform/airflow-operator#38]
`docs/quickstart.md` references files under `manifests` dir, which does not exist. 

Either:
1) Tell me which files are the ones which are referenced in the quickstart guide but no longer exist under those names, then I am happy to update docs to point to correct files.
2) Update `docs/quickstart.md` to point to correct location

**Comment by barney-s** [comment]
thanks for this issue. It is out of date. will update.
Its a little more involved than pointing to the right dir. will verify the steps and update.

**Comment by barney-s** [comment]
Fixed. Please retest.
@chris-vest
