### ISSUE TITLE
[Question] Redis Required for k8s Executor?

### ISSUE THREAD

**Issue by EamonKeane** [GoogleCloudPlatform/airflow-operator#4]
This looks great. Is redis required for the k8s executor?

**Comment by barney-s** [comment]
No. 
An example: 
https://github.com/GoogleCloudPlatform/airflow-operator/blob/master/hack/sample/mysql-k8s/cluster.yaml

**Comment by EamonKeane** [comment]
Thanks. It'd be nice to have an example showing the workflow for changing a variable in airflow.cfg and re-deploying.

**Comment by barney-s** [comment]
The operator doesnt support changing airflow.cfg variables.
We need to add that feature. Will add a feature request for that.

**Comment by barney-s** [comment]
Created https://github.com/GoogleCloudPlatform/airflow-operator/issues/8 to track this feature request.
