### ISSUE TITLE
Clarify docs/api.md regarding field CredSecretRef

### ISSUE THREAD

**Issue by chris-vest** [GoogleCloudPlatform/airflow-operator#40]
Attempting to set up `git-sync` to use a username and OAuth token, but cannot seem to figure out how to use the `CredSecretRef` field - can we clarify the docs, perhaps providing an example? 

I have tried to set the field using the  `UID` / `selfLink` to the secret containing the token / password, however am getting the following error:

```spec.dags.git.cred in body must be of type object: "string"```

Any clarification would be appreciated!

**Comment by barney-s** [comment]
Tje CredSecretRef needs to be used like this 
```yaml
.spec.dags.git
     cred:
         name: secretname
```

The secret needs to have the git password in `password` field.

The `.git.repo`, `.git.user` and  `.git.cred.name` secret's `password` are used to setup git creds using `git credential approve` and `url=%v\nusername=%v\npassword=%v\n`

**Comment by chris-vest** [comment]
This works perfectly, thanks very much!
