### ISSUE TITLE
airflow operator question

### ISSUE THREAD

**Issue by feng-tao** [GoogleCloudPlatform/airflow-operator#43]
Hi @barney-s ,

We(Lyft) are exploring running airflow on k8s internally. I wonder whether google has run this repo in production. Any hiccups encounter so far?

Thanks,
-Tao

**Comment by barney-s** [comment]
This would be perfect for managing airflow on k8s especially across teams.
In google composer team evaluated this internally.  They had already built a hand rolled solution using google cloud DM. 

Hiccups:
1.10 support for k8s executor is still in progress.
@dimberman and me were planning to fix it. 

Would be glad to support you in your evaluation.
