### ISSUE TITLE
manifests/install_controller.yaml links to wrong image tag

### ISSUE THREAD

**Issue by pblaas** [GoogleCloudPlatform/airflow-operator#6]
Hi,

The image tag in manifests/install_controller.yaml from the example in the readme points to tag alpha which doesn't seem to exist.  Changing this to v1alpha1 seemed to fix this.

**Comment by barney-s** [comment]
Thanks for pointing out. Fixed via: https://github.com/GoogleCloudPlatform/airflow-operator/commit/c9666959ae56ac583262dbcf7b7c46ba9d37efa7
