### ISSUE TITLE
Airflow Operator + Postgres Cloud SQL - Airflow UI pod won't restart after it is killed

### ISSUE THREAD

**Issue by jcunhasilva** [GoogleCloudPlatform/airflow-operator#65]
After we start the Airflow Operator with the base and cluster configurations, using the Postgres Cloud SQL Configuration, an error is thrown in the "postgres-dbcreate" init container whenever the Airflow UI pod is restarted:
`Database already exists`

This container needs to check if the database already exists before creating the database and tables.

**Comment by barney-s** [comment]
Thanks for the fix.
