### ISSUE TITLE
Expose airflow.cfg config settings via CRs

### ISSUE THREAD

**Issue by barney-s** [GoogleCloudPlatform/airflow-operator#8]
possible options:
1. via airflow env variables
2. via airflow.cfg map[string]string stored in config-map

**Comment by EamonKeane** [comment]
I might have time to do this, see my thoughts below... although I'm new to CRDs so bear with me. 

What should be the approach - enumerating the sections and values in the `AirflowCluster` spec and storing as env-vars, or copying a file and storing as a configmap, or both?

I think a standalone `airflow.cfg` is the easiest to reason about (and test locally) than having a lot of env variables. The env variables have to be replicated in the UI, scheduler and k8s workers while a single configmap does the job for all three and keeps the lines of yaml down.

There is a lot of config validation logic in <https://github.com/apache/incubator-airflow/blob/master/airflow/configuration.py>. Should the CR attempt to validate that or let it be validated by airflow? Initially I'd suggest not to duplicate the validation logic.

There's a go package similar to python's `backports.configparser` for parsing the config file:
https://github.com/alyu/configparser

This gives you the sections and values as map[string]string. Although if it's just a file that'll be stored as a configmap, technically (I think) you wouldn't need to parse it. If a new `AirflowCluster` configuration was applied, the old configmap could just be deleted and the new one created from the file (perhaps by checking file size or date modified) or a new configmap with the name e.g. `airflow-cm-current-seconds` could be created with the deployments/statefulsets updated appropriately.

**Comment by EamonKeane** [comment]
hi @barney-s sorry I haven't found the time, so I've been sticking with just installing via helm. So feel free to close or take it up yourself.

**Comment by barney-s** [comment]
Inject airflow env's via  `airflowcluster.spec.config.airflow` 

```yaml
apiVersion: airflow.k8s.io/v1alpha1
kind: AirflowCluster
metadata:
  name: mc-cluster
spec:
  executor: Celery
  config:
    airflow:
      AIRFLOW_SOME_CONFIG: SomeValue
...
```
